### ISSUE TITLE
Error running "npm run helper:add"

### ISSUE THREAD

**Issue by alexharris** [stefanjudis/tiny-helpers#101]
Trying to add a helper, following the instructions from the readme. All is well until I run `npm run helper:add`, and I get the following error:

```
TypeError: Object.fromEntries is not a function
    at getHelpersFromHelpersJSON (/Users/alexharris/Sites/tiny-helpers/lib/helpers.js:22:17)
    at getHelpers (/Users/alexharris/Sites/tiny-helpers/lib/helpers.js:9:15)
    at /Users/alexharris/Sites/tiny-helpers/scripts/add-helper.js:6:32
    at Object.<anonymous> (/Users/alexharris/Sites/tiny-helpers/scripts/add-helper.js:59:3)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
```

In the meantime, can I add a helper by just adding JSON directly to helpers.json?

**Comment by alexharris** [comment]
Resolved by upgrading Node!
