### ISSUE TITLE
Cannot run npm run helper:add

### ISSUE THREAD

**Issue by geongeorge** [stefanjudis/tiny-helpers#143]
npm run helper:add

> tiny-helpers@1.0.0 helper:add /Users/geongeorge/Code/tiny-helpers
> node ./scripts/add-helper.js

(node:32597) ExperimentalWarning: The fs.promises API is experimental
TypeError: Object.fromEntries is not a function
    at getHelpersFromHelpersJSON (/Users/geongeorge/Code/tiny-helpers/lib/helpers.js:22:17)
    at getHelpers (/Users/geongeorge/Code/tiny-helpers/lib/helpers.js:9:15)
    at /Users/geongeorge/Code/tiny-helpers/scripts/add-helper.js:6:32
    at Object.<anonymous> (/Users/geongeorge/Code/tiny-helpers/scripts/add-helper.js:59:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by stefanjudis** [comment]
@geongeorge Thanks so much for trying to contribute. :) 

I assume you're running on an older node version?

<img width="816" alt="Screen Shot 2020-01-31 at 17 40 20" src="https://user-images.githubusercontent.com/962099/73557099-e9df0100-4450-11ea-82c5-4df63c42b4ec.png">

As pointed out in the README.md and in issue #101 v12 is needed. :) (I might add a version check to the script soon 🙈) Happy to reopen this issue if the problem is something else. :)
